name: CI

on:
  pull_request:
    branches: [ main ]
  # Możliwość ręcznego uruchomienia
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install -g html-validator-cli

      - name: Validate HTML
        run: html-validator --file index.html --verbose

      - name: Validate CSS
        run: |
          npm install -g stylelint stylelint-config-standard
          echo '{
            "extends": "stylelint-config-standard",
            "rules": {
              "indentation": 2,
              "string-quotes": "double",
              "no-duplicate-selectors": true,
              "color-hex-case": "lower",
              "color-hex-length": "short",
              "selector-combinator-space-after": "always",
              "declaration-block-trailing-semicolon": "always",
              "declaration-colon-space-before": "never",
              "declaration-colon-space-after": "always",
              "property-no-vendor-prefix": null,
              "value-no-vendor-prefix": null,
              "number-leading-zero": "always",
              "function-url-quotes": "always",
              "selector-pseudo-element-colon-notation": "double",
              "no-descending-specificity": null,
              "no-duplicate-at-import-rules": true,
              "declaration-block-no-duplicate-properties": true,
              "font-family-no-duplicate-names": true,
              "selector-class-pattern": null,
              "keyframes-name-pattern": null,
              "alpha-value-notation": null,
              "color-function-notation": null
            }
          }' > .stylelintrc.json
          npx stylelint "*.css" --fix || true
