name: CI

on:
  pull_request:
    branches: [ main ]
  # Możliwość ręcznego uruchomienia
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install -g html-validator-cli broken-link-checker

      - name: Validate HTML
        run: html-validator --file index.html --verbose

      - name: Start local server
        run: python -m http.server 8080 --bind 0.0.0.0 &

      - name: Wait for server
        run: |
          sleep 5
          curl http://127.0.0.1:8080 -I || exit 1

      - name: Check for broken links
        run: blc http://127.0.0.1:8080 -ro
